### print(f'abc {var}')

In [2]:
a=2
b=5
print('Here is a new line \n2nd line')
print('\nThe addition is',a+b, '-> non-standard')
print(f'\nThe addition is {a+b} -> standard way')

Here is a new line 
2nd line

The addition is 7 -> non-standard

The addition is 7 -> standard way


In [3]:
name = 'Mamun'
friend = 'His name is '+ name
print(friend)
print('quotation : \"')

index = friend.index('m')
print(f'Index of m: {index}')

index = friend.index('Mamun')
print(f'Index of m: {index}')

new_friend = friend.replace('Mamun', 'Shah')
print(new_friend)
print(4%2)
print(11%2)

His name is Mamun
quotation : "
Index of m: 6
Index of m: 12
His name is Shah
0
1


In [4]:
print(dir(friend))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [5]:
from math import ceil, floor, sqrt
print(f'ceil 3.7: {ceil(3.7)}')
print(f'floor 3.7: {floor(3.7)}')
print(f'sqrt 0.36: {sqrt(0.36)}\n')

print(2**4)
print(pow(2,4))

print(2**0.4)
print(pow(2,0.4))


print(int(3.4))
print(int(3.5))
print(int(3.99))

ceil 3.7: 4
floor 3.7: 3
sqrt 0.36: 0.6

16
16
1.3195079107728942
1.3195079107728942
3
3
3


In [6]:
number = input('Input Number')
print(f'Your number {number}')

name = input('Input Name')
print(f'Your Name {name}')

Input Number 25


Your number 25


Input Name Shah


Your Name Shah


### List []

In [8]:
data = [0,1,2,3,4]
print(f'Second Element: {data[1]}')
print('\n')

data.append(5)
print(f'data: {data}')

print('\n')
print(f'Last Element: {data[-1]}')


print('\n')
print(f'Data from index3(included) onward: {data[3:]}')
print(f'Data up to index3 (excluded): {data[:3]}')
print(f'Data index1 to index4(excluded) : {data[1:4]}')


list1 = ['a','b','c']
list2 = ['x','y','z']
list1.extend(list2)
print(f'\nlist1: {list1}\n')


Second Element: 1


data: [0, 1, 2, 3, 4, 5]


Last Element: 5


Data from index3(included) onward: [3, 4, 5]
Data up to index3 (excluded): [0, 1, 2]
Data index1 to index4(excluded) : [1, 2, 3]

list1: ['a', 'b', 'c', 'x', 'y', 'z']



In [9]:
numbers = [
    [1,2,3], # row 0
    [4,5,6], #row 1
    [7,8,9]
]

numbers[1][1] # numbers row, col

5

In [10]:
print(dir(list1))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


### Tuple () : (fixed, doesn't support item assignment, you can't change values)

In [12]:
d = (3,4)
print(d)


(3, 4)


### Dictionary : {key : val}

In [14]:
price = {'fish' : 30, 'meat' : 50}
print(price)
dir(price)[-11:] # Last 11 valid attributes and methods

{'fish': 30, 'meat': 50}


['clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [15]:
print(f'keys: {price.keys()}')
print(f'values: {price.values()}')
print(f'items: {price.items()}')

keys: dict_keys(['fish', 'meat'])
values: dict_values([30, 50])
items: dict_items([('fish', 30), ('meat', 50)])


In [16]:
fish = price['fish']
print(f'fish: {fish}')

meat = price.get('meat', 'default')
print(f'meat: {meat}')

laptop = price.get('laptop', 'default')
print(f'laptop: {laptop}')

tv = price.get('tv')
print(f'tv: {tv}')


fish: 30
meat: 50
laptop: default
tv: None


### try: do it, except Exception as e: dont and print

In [18]:
try:
    f = 4
    print(f)
except:
    print('error')


try:
    temp0 = temp0+1
    print(temp0)
except Exception as e:
    print(e)

4
name 'temp0' is not defined


In [19]:
try:
    num = int(input("Enter a number: "))
    result = 10 / num
    print(f"Result: {result}")
except ValueError:
    print("Invalid input: Please enter a whole number.")
except ZeroDivisionError:
    print("Error: Cannot divide by zero.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
else:
    print("Division successful.")
finally:
    print("Execution complete.")

Enter a number:  Shah


Invalid input: Please enter a whole number.
Execution complete.


### Open Close File

In [21]:
new_file = open('new_file.txt', 'a')
new_file.write ('This is python writing - Line 0')
new_file.write ('\nThis is python writing - Line 1')
new_file.write ('\nThis is python writing - Line 2')
new_file.write ('\nThis is python writing - Line 3')
new_file.write ('\nThis is python writing - Line 4')
new_file.write ('\nThis is python writing - Line 4')
new_file.close()

In [22]:
new_file = open('new_file.txt', 'r')

options = dir(new_file)
print(options[-26:])
new_file.close()


['buffer', 'close', 'closed', 'detach', 'encoding', 'errors', 'fileno', 'flush', 'isatty', 'line_buffering', 'mode', 'name', 'newlines', 'read', 'readable', 'readline', 'readlines', 'reconfigure', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'write_through', 'writelines']


In [23]:
# Read entire file as a single string
with open('new_file.txt', 'r') as f:
    data = f.read()

print(data)

This is python writing - Line 0
This is python writing - Line 1
This is python writing - Line 2
This is python writing - Line 3
This is python writing - Line 4
This is python writing - Line 4This is python writing - Line 0
This is python writing - Line 1
This is python writing - Line 2
This is python writing - Line 3
This is python writing - Line 4
This is python writing - Line 4This is python writing - Line 0
This is python writing - Line 1
This is python writing - Line 2
This is python writing - Line 3
This is python writing - Line 4
This is python writing - Line 4


In [24]:
# Read file into a list of lines
with open('new_file.txt', 'r') as f:
    data = f.readlines()
print(data)   # ["first line\n", "second line\n", ...]

['This is python writing - Line 0\n', 'This is python writing - Line 1\n', 'This is python writing - Line 2\n', 'This is python writing - Line 3\n', 'This is python writing - Line 4\n', 'This is python writing - Line 4This is python writing - Line 0\n', 'This is python writing - Line 1\n', 'This is python writing - Line 2\n', 'This is python writing - Line 3\n', 'This is python writing - Line 4\n', 'This is python writing - Line 4This is python writing - Line 0\n', 'This is python writing - Line 1\n', 'This is python writing - Line 2\n', 'This is python writing - Line 3\n', 'This is python writing - Line 4\n', 'This is python writing - Line 4']


### numpy

In [26]:
# NumPy Tutorial 🚀
import numpy as np

# -------------------------------
# 1. Creating Arrays
# -------------------------------
print("1. Creating Arrays")
a = np.array([1, 2, 3])                # from Python list
b = np.array([[1, 2], [3, 4]])         # 2D array
c = np.zeros((2, 3))                    # 2x3 of zeros
d = np.ones((3, 3))                     # 3x3 of ones
e = np.eye(4)                           # 4x4 identity matrix
f = np.arange(0, 10, 2)                 # range: 0 to 10 step 2
g = np.linspace(0, 1, 5)                # 5 points evenly spaced between 0 and 1

print("a:", a)
print("b:\n", b)
print("zeros:\n", c)
print("ones:\n", d)
print("identity:\n", e)
print("arange:", f)
print("linspace:", g)

1. Creating Arrays
a: [1 2 3]
b:
 [[1 2]
 [3 4]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


In [27]:
# -------------------------------
# 2. Array Properties
# -------------------------------
print("\n2. Array Properties")
print("Shape of b:", b.shape)
print("Data type of b:", b.dtype)
print("Number of elements in b:", b.size)

# -------------------------------
# 3. Indexing and Slicing
# -------------------------------
print("\n3. Indexing and Slicing")
print("b[0, 1] =", b[0, 1])            # element at row 0, col 1
print("Row 0 of b:", b[0, :])
print("Column 1 of b:", b[:, 1])


2. Array Properties
Shape of b: (2, 2)
Data type of b: int32
Number of elements in b: 4

3. Indexing and Slicing
b[0, 1] = 2
Row 0 of b: [1 2]
Column 1 of b: [2 4]


In [28]:
# -------------------------------
# 4. Math Operations
# -------------------------------
print("\n4. Math Operations")
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
print("x + y =", x + y)
print("x - y =", x - y)
print("x * y =", x * y)                # elementwise multiply
print("x / y =", x / y)
print("x ** 2 =", x ** 2)
print("np.sqrt(x):", np.sqrt(x))

# -------------------------------
# 5. Matrix Operations
# -------------------------------
print("\n5. Matrix Operations")
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print("m1 + m2:\n", m1 + m2)
print("m1 dot m2:\n", np.dot(m1, m2))  # matrix multiplication
print("Transpose of m1:\n", m1.T)
print("Inverse of m1:\n", np.linalg.inv(m1))


4. Math Operations
x + y = [11 22 33]
x - y = [ -9 -18 -27]
x * y = [10 40 90]
x / y = [0.1 0.1 0.1]
x ** 2 = [1 4 9]
np.sqrt(x): [1.         1.41421356 1.73205081]

5. Matrix Operations
m1 + m2:
 [[ 6  8]
 [10 12]]
m1 dot m2:
 [[19 22]
 [43 50]]
Transpose of m1:
 [[1 3]
 [2 4]]
Inverse of m1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
# -------------------------------
# 6. Statistics
# -------------------------------
print("\n6. Statistics")
stats = np.array([[1, 2, 3], [4, 5, 6]])
print("Mean:", np.mean(stats))
print("Sum over columns:", np.sum(stats, axis=0))
print("Max over rows:", np.max(stats, axis=1))

# -------------------------------
# 7. Random Numbers
# -------------------------------
print("\n7. Random Numbers")
print("Random float [0,1):", np.random.rand())
print("Random 2x2:\n", np.random.rand(2, 2))
print("Random integers 0-9:", np.random.randint(0, 10, (3, 3)))




6. Statistics
Mean: 3.5
Sum over columns: [5 7 9]
Max over rows: [3 6]

7. Random Numbers
Random float [0,1): 0.5815071624397061
Random 2x2:
 [[0.61328635 0.59998344]
 [0.58605204 0.92811471]]
Random integers 0-9: [[3 0 9]
 [8 1 9]
 [2 0 1]]


In [30]:
# -------------------------------
# 8. Reshaping and Flattening
# -------------------------------
print("\n8. Reshaping and Flattening")
arr = np.arange(12)                     # 0..11
print("Original:", arr)
reshaped = arr.reshape(3, 4)            # reshape to 3x4
print("Reshaped 3x4:\n", reshaped)
print("Flattened:", reshaped.flatten())

# -------------------------------
# 9. Boolean Masking
# -------------------------------
print("\n9. Boolean Masking")
data = np.array([10, 20, 30, 40, 50])
mask = data > 25
print("Mask:", mask)
print("Values > 25:", data[mask])

# -------------------------------
# 10. Broadcasting
# -------------------------------
print("\n10. Broadcasting")
mat = np.ones((3, 3))
vec = np.array([1, 2, 3])
print("mat:\n", mat)
print("vec:", vec)
print("mat + vec:\n", mat + vec)        # vec added to each row



8. Reshaping and Flattening
Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

9. Boolean Masking
Mask: [False False  True  True  True]
Values > 25: [30 40 50]

10. Broadcasting
mat:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
vec: [1 2 3]
mat + vec:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


### pandas

In [32]:
# Pandas Tutorial 📊
import pandas as pd
import numpy as np

# -------------------------------
# 1. Creating Series
# -------------------------------
print("1. Creating Series")
s = pd.Series([10, 20, 30, 40], index=["a", "b", "c", "d"])
print(s)
print("Access element by label:", s["b"])
print("Access element by index:", s.iloc[2])

# -------------------------------
# 2. Creating DataFrames
# -------------------------------
print("\n2. Creating DataFrames")
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "City": ["NYC", "LA", "Chicago", "Houston"]
}
df = pd.DataFrame(data)
print(df)

# -------------------------------
# 7. Basic Statistics
# -------------------------------
print("\n7. Basic Statistics")
print("Mean age:", df["Age"].mean())
print("Summary:\n", df.describe())

# -------------------------------
# 8. Sorting
# -------------------------------
print("\n8. Sorting")
print("Sort by Age:\n", df.sort_values("Age", ascending=False))

# -------------------------------
# 9. GroupBy
# -------------------------------
print("\n9. GroupBy")
df2 = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Finance"],
    "Salary": [60000, 65000, 50000, 52000, 70000],
    "Experience": [2, 3, 5, 7, 10]
})
print(df2)
print("Mean salary by department:\n", df2.groupby("Department")["Salary"].mean())

# -------------------------------
# 10. Merging / Joining
# -------------------------------
print("\n10. Merging / Joining")
employees = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Dept": ["IT", "HR", "Finance"]
})
salaries = pd.DataFrame({
    "Dept": ["IT", "HR", "Finance"],
    "Salary": [60000, 50000, 70000]
})
merged = pd.merge(employees, salaries, on="Dept", how="left")
print(merged)

# -------------------------------
# 11. Handling Missing Data
# -------------------------------
print("\n11. Handling Missing Data")
df3 = pd.DataFrame({
    "A": [1, 2, np.nan, 4],
    "B": [5, np.nan, np.nan, 8]
})
print("Original:\n", df3)
print("Drop rows with NaN:\n", df3.dropna())
print("Fill NaN with 0:\n", df3.fillna(0))
print("Fill NaN with column mean:\n", df3.fillna(df3.mean(numeric_only=True)))

# -------------------------------
# 12. Reading / Writing CSV
# -------------------------------
print("\n12. Reading / Writing CSV")
# df.to_csv("example.csv", index=False)  # save
# loaded = pd.read_csv("example.csv")    # load
# print(loaded)
print("Use df.to_csv(...) to write and pd.read_csv(...) to read")


1. Creating Series
a    10
b    20
c    30
d    40
dtype: int64
Access element by label: 20
Access element by index: 30

2. Creating DataFrames
      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40  Houston

7. Basic Statistics
Mean age: 32.5
Summary:
              Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

8. Sorting
Sort by Age:
       Name  Age     City
3    David   40  Houston
2  Charlie   35  Chicago
1      Bob   30       LA
0    Alice   25      NYC

9. GroupBy
  Department  Salary  Experience
0         IT   60000           2
1         IT   65000           3
2         HR   50000           5
3         HR   52000           7
4    Finance   70000          10
Mean salary by department:
 Department
Finance    70000.0
HR         51000.0
IT         62500.0
Name: Salary, dtype: float64

10. Merging / Joining
      Name     Dept  Sa

In [33]:
# -------------------------------
# 3. Inspecting Data
# -------------------------------
print("\n3. Inspecting Data")
print("Head:\n", df.head(2))
print("Shape:", df.shape)
print("Columns:", df.columns)
print("Info:")
print(df.info())

# -------------------------------
# 4. Selecting Data
# -------------------------------
print("\n4. Selecting Data")
print("Single column:\n", df["Name"])
print("Multiple columns:\n", df[["Name", "City"]])
print("Row by label:\n", df.loc[1])
print("Row by position:\n", df.iloc[2])


3. Inspecting Data
Head:
     Name  Age City
0  Alice   25  NYC
1    Bob   30   LA
Shape: (4, 3)
Columns: Index(['Name', 'Age', 'City'], dtype='object')
Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes
None

4. Selecting Data
Single column:
 0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
Multiple columns:
       Name     City
0    Alice      NYC
1      Bob       LA
2  Charlie  Chicago
3    David  Houston
Row by label:
 Name    Bob
Age      30
City     LA
Name: 1, dtype: object
Row by position:
 Name    Charlie
Age          35
City    Chicago
Name: 2, dtype: object


In [34]:
# -------------------------------
# 5. Filtering Rows
# -------------------------------
print("\n5. Filtering Rows")
print("Age > 30:\n", df[df["Age"] > 30])
print("City == LA:\n", df[df["City"] == "LA"])

# -------------------------------
# 6. Adding / Modifying Columns
# -------------------------------
print("\n6. Adding / Modifying Columns")
df["Age in 5 years"] = df["Age"] + 5
df["Senior"] = df["Age"] > 35
print(df)


5. Filtering Rows
Age > 30:
       Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston
City == LA:
   Name  Age City
1  Bob   30   LA

6. Adding / Modifying Columns
      Name  Age     City  Age in 5 years  Senior
0    Alice   25      NYC              30   False
1      Bob   30       LA              35   False
2  Charlie   35  Chicago              40   False
3    David   40  Houston              45    True


### function

In [36]:
# Python Functions Tutorial ⚡

# -------------------------------
# 1. Basic Function
# -------------------------------
def greet():
    print("Hello, world!")

greet()

# -------------------------------
# 2. Function with Parameters
# -------------------------------
def greet_person(name):
    print(f"Hello, {name}!")

greet_person("Alice")
greet_person("Bob")

Hello, world!
Hello, Alice!
Hello, Bob!


In [37]:
# -------------------------------
# 3. Function with Return Value
# -------------------------------
def square(x):
    return x * x

result = square(5)
print("Square of 5:", result)

# -------------------------------
# 4. Multiple Parameters
# -------------------------------
def add(a, b):
    return a + b

print("2 + 3 =", add(2, 3))

# -------------------------------
# 5. Default Arguments
# -------------------------------
def power(base, exp=2):
    return base ** exp

print("power(3):", power(3))      # uses default exp=2
print("power(3, 3):", power(3, 3))

Square of 5: 25
2 + 3 = 5
power(3): 9
power(3, 3): 27


In [38]:
# -------------------------------
# 6. Keyword Arguments
# -------------------------------
def introduce(name, age, city):
    print(f"My name is {name}, I'm {age}, and I live in {city}.")

introduce(age=25, name="Charlie", city="NYC")

# -------------------------------
# 7. Variable Number of Arguments (*args)
# -------------------------------
def sum_all(*args):
    return sum(args)

print("sum_all(1,2,3,4,5):", sum_all(1, 2, 3, 4, 5))

# -------------------------------
# 8. Variable Keyword Arguments (**kwargs)
# -------------------------------
def profile(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

profile(name="David", age=30, city="LA")

My name is Charlie, I'm 25, and I live in NYC.
sum_all(1,2,3,4,5): 15
name: David
age: 30
city: LA


In [39]:
# -------------------------------
# 9. Lambda (Anonymous Functions)
# -------------------------------
double = lambda x: x * 2
print("double(7):", double(7))

# Use with map/filter
nums = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, nums))
even = list(filter(lambda x: x % 2 == 0, nums))

print("Squared:", squared)
print("Even:", even)

double(7): 14
Squared: [1, 4, 9, 16, 25]
Even: [2, 4]


In [40]:
# -------------------------------
# 10. Functions Inside Functions
# -------------------------------
def outer_function(text):
    def inner_function():
        return text.upper()
    return inner_function()

print("Inner function result:", outer_function("hello"))

Inner function result: HELLO


In [41]:
# -------------------------------
# 11. Functions as Arguments
# -------------------------------
def apply(func, value):
    return func(value)

print("apply(square, 6):", apply(square, 6))

# -------------------------------
# 12. Recursive Function
# -------------------------------
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

print("Factorial of 5:", factorial(5))

# -------------------------------
# 13. Docstrings
# -------------------------------
def divide(a, b):
    """
    Divides two numbers.
    
    Parameters:
        a (int/float): numerator
        b (int/float): denominator
    
    Returns:
        float: result of division
    """
    return a / b

print("divide(10,2):", divide(10, 2))
print("Help on divide:")
help(divide)


apply(square, 6): 36
Factorial of 5: 120
divide(10,2): 5.0
Help on divide:
Help on function divide in module __main__:

divide(a, b)
    Divides two numbers.
    
    Parameters:
        a (int/float): numerator
        b (int/float): denominator
    
    Returns:
        float: result of division



#### Using *args (variable positional arguments)

In [43]:
def add_numbers(*args):
    print("args as tuple:", args)
    return sum(args)

print(add_numbers(1, 2, 3))
print(add_numbers(10, 20, 30, 40))


args as tuple: (1, 2, 3)
6
args as tuple: (10, 20, 30, 40)
100


In [44]:
#### Using **kwargs (variable keyword arguments)

In [45]:
def print_profile(**kwargs):
    print("kwargs as dict:", kwargs)
    for key, value in kwargs.items():
        print(f"{key}: {value}")

print_profile(name="Alice", age=25, city="NYC")


kwargs as dict: {'name': 'Alice', 'age': 25, 'city': 'NYC'}
name: Alice
age: 25
city: NYC


#### Combining *args and **kwargs

In [47]:
def demo_func(*args, **kwargs):
    print("args:", args)
    print("kwargs:", kwargs)

demo_func(1, 2, 3, name="Bob", age=30)


args: (1, 2, 3)
kwargs: {'name': 'Bob', 'age': 30}


#### Forwarding Arguments

In [49]:
def greet(greeting, name):
    print(f"{greeting}, {name}!")

def wrapper(*args, **kwargs):
    print("Wrapper adds logging...")
    return greet(*args, **kwargs)

wrapper("Hello", name="Charlie")


Wrapper adds logging...
Hello, Charlie!


#### Mixing with Normal Arguments

In [51]:
def order(item, qty=1, *args, **kwargs):
    print(f"Item: {item}, Qty: {qty}")
    print("Extra positional:", args)
    print("Extra keyword:", kwargs)

order("Book", 2, "Express shipping", "Gift wrap", address="NYC", discount=0.1)


Item: Book, Qty: 2
Extra positional: ('Express shipping', 'Gift wrap')
Extra keyword: {'address': 'NYC', 'discount': 0.1}


#### Fixing arguments for math functions

In [53]:
from functools import partial
import math

# Normal pow(base, exp)
print(pow(2, 3))  # 8
print('_'*25)

# Create a "square" function by fixing exp=2
square = partial(pow, exp=2)
print(square(5))  # 25
print('_'*25)

# Cube function
cube = partial(pow, exp=3)
print(cube(4))    # 64
print('_'*25)



# Using with higher-order functions

def multiply(x, y):
    return x * y

double = partial(multiply, 2)
triple = partial(multiply, 3)

print(double(5))  # 10
print(triple(5))  # 15
print('_'*25)

# Simplifying function calls with many parameters

def order(item, qty, discount, tax):
    return f"{qty}x {item} with {discount*100:.0f}% discount and {tax*100:.0f}% tax"

# Fix tax and discount
order_with_tax = partial(order, discount=0.1, tax=0.07)

print(order_with_tax("Book", 3))
print(order_with_tax("Laptop", 1))




8
_________________________
25
_________________________
64
_________________________
10
15
_________________________
3x Book with 10% discount and 7% tax
1x Laptop with 10% discount and 7% tax


#### Pre-configuring built-in functions

In [55]:
from functools import partial

print_with_comma = partial(print, sep=", ")
print_with_comma("Alice", "Bob", "Charlie")


Alice, Bob, Charlie


### class

In [57]:
# Python Classes Tutorial 🏗️

# -------------------------------
# 1. A Basic Class
# -------------------------------
class Person:
    pass

p1 = Person()
print("Created a Person object:", p1)

# -------------------------------
# 2. Adding Attributes
# -------------------------------
class Person:
    def __init__(self, name, age):
        self.name = name    # instance attribute
        self.age = age

p2 = Person("Alice", 25)
print(f"Name: {p2.name}, Age: {p2.age}")

Created a Person object: <__main__.Person object at 0x00000185FFBF21D0>
Name: Alice, Age: 25


In [58]:
# -------------------------------
# 3. Adding Methods
# -------------------------------
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def greet(self):
        return f"Hello, I'm {self.name} and I'm {self.age} years old."

p3 = Person("Bob", 30)
print(p3.greet())

# -------------------------------
# 4. Class Attributes vs Instance Attributes
# -------------------------------
class Dog:
    species = "Canis familiaris"   # class attribute
    
    def __init__(self, name):
        self.name = name          # instance attribute

dog1 = Dog("Fido")
dog2 = Dog("Buddy")

print(dog1.name, "-", dog1.species)
print(dog2.name, "-", dog2.species)

Hello, I'm Bob and I'm 30 years old.
Fido - Canis familiaris
Buddy - Canis familiaris


In [59]:
# -------------------------------
# 5. Special Methods (__str__, __len__, etc.)
# -------------------------------
class Book:
    def __init__(self, title, pages):
        self.title = title
        self.pages = pages
    
    def __str__(self):
        return f"Book: {self.title} ({self.pages} pages)"
    
    def __len__(self):
        return self.pages

b1 = Book("Python Basics", 250)
print(str(b1))
print("Length of book:", len(b1))

Book: Python Basics (250 pages)
Length of book: 250


In [60]:
# -------------------------------
# 6. Encapsulation (Private variables)
# -------------------------------
class BankAccount:
    def __init__(self, owner, balance=0):
        self.owner = owner
        self.__balance = balance   # private attribute (convention: __var)
    
    def deposit(self, amount):
        self.__balance += amount
        return self.__balance
    
    def withdraw(self, amount):
        if amount <= self.__balance:
            self.__balance -= amount
            return self.__balance
        else:
            return "Insufficient funds"
    
    def get_balance(self):
        return self.__balance

acct = BankAccount("Charlie", 100)
print(acct.deposit(50))
print(acct.withdraw(30))
print("Balance:", acct.get_balance())

150
120
Balance: 120


In [61]:
# -------------------------------
# 7. Inheritance
# -------------------------------
class Animal:
    def __init__(self, name):
        self.name = name
    
    def speak(self):
        return "..."

class Dog(Animal):
    def speak(self):
        return "Woof!"

class Cat(Animal):
    def speak(self):
        return "Meow!"

animals = [Dog("Fido"), Cat("Whiskers")]
for a in animals:
    print(a.name, "says", a.speak())

Fido says Woof!
Whiskers says Meow!


In [62]:
# -------------------------------
# 8. Multiple Inheritance
# -------------------------------
class Flyer:
    def fly(self):
        return "I can fly!"

class Swimmer:
    def swim(self):
        return "I can swim!"

class Duck(Flyer, Swimmer):
    def sound(self):
        return "Quack!"

d = Duck()
print(d.fly(), d.swim(), d.sound())

I can fly! I can swim! Quack!


In [63]:
# -------------------------------
# 9. Class Methods and Static Methods
# -------------------------------
class MathUtils:
    @staticmethod
    def add(a, b):
        return a + b
    
    @classmethod
    def description(cls):
        return f"This is {cls.__name__}, providing math utilities."

print(MathUtils.add(2, 3))
print(MathUtils.description())

5
This is MathUtils, providing math utilities.


In [64]:
# -------------------------------
# 10. Properties (getter/setter)
# -------------------------------
class Celsius:
    def __init__(self, temperature=0):
        self._temperature = temperature
    
    @property #getter
    def temperature(self):
        return self._temperature
    
    @temperature.setter
    def temperature(self, value):
        if value < -273.15:
            raise ValueError("Temperature below -273.15 is not possible")
        self._temperature = value

c = Celsius()
c.temperature = 25
print("Temp in Celsius:", c.temperature)
# c.temperature = -300  # will raise ValueError

Temp in Celsius: 25


In [65]:
dir(c)[-2:]

['_temperature', 'temperature']

## Decorator

#### Basic Decorator

In [68]:
def my_decorator(func):
    def wrapper():
        print("Before function runs")
        func()
        print("After function runs")
    return wrapper

@my_decorator
def say_hello():
    print("Hello!")

say_hello()


Before function runs
Hello!
After function runs


#### Decorator with Arguments

In [70]:
def repeat(n):
    def decorator(func):
        def wrapper(*args, **kwargs):
            for _ in range(n):
                func(*args, **kwargs)
        return wrapper
    return decorator

@repeat(3)
def greet(name):
    print(f"Hello, {name}!")

greet("Alice")


Hello, Alice!
Hello, Alice!
Hello, Alice!


#### Preserving Function Metadata (functools.wraps)

In [72]:
from functools import wraps

def debug(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print(f"Calling {func.__name__} with args={args}, kwargs={kwargs}")
        return func(*args, **kwargs)
    return wrapper

@debug
def add(a, b):
    """Add two numbers"""
    return a + b

print(add(2, 3))
print(add.__name__)    # preserved: "add"
print(add.__doc__)     # preserved: "Add two numbers"


Calling add with args=(2, 3), kwargs={}
5
add
Add two numbers


#### Real-World Example: Timing a Function

In [74]:
import time
from functools import wraps

def timer(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"{func.__name__} ran in {end - start:.4f} seconds")
        return result
    return wrapper

@timer
def slow_function():
    time.sleep(2)
    return "Done!"

print(slow_function())


slow_function ran in 2.0082 seconds
Done!


#### Real-World Example: Authentication Check

In [76]:
def require_admin(func):
    @wraps(func)
    def wrapper(user, *args, **kwargs):
        if user != "admin":
            print("Access denied!")
            return None
        return func(user, *args, **kwargs)
    return wrapper

@require_admin
def delete_user(user, target):
    print(f"{user} deleted {target}")

delete_user("guest", "Alice")   # Access denied
delete_user("admin", "Bob")     # Works


Access denied!
admin deleted Bob


#### Stacking Multiple Decorators

In [78]:
def bold(func):
    @wraps(func)
    def wrapper():
        return "<b>" + func() + "</b>"
    return wrapper

def italic(func):
    @wraps(func)
    def wrapper():
        return "<i>" + func() + "</i>"
    return wrapper

@bold
@italic
def text():
    return "Hello"

print(text())   # <b><i>Hello</i></b>


<b><i>Hello</i></b>


#### The Problem Without @wraps

##### Example without @wraps

In [81]:
def debug(func):
    def wrapper(*args, **kwargs):
        print(f"Calling {func.__name__} with {args}")
        return func(*args, **kwargs)
    return wrapper

@debug
def add(a, b):
    """Add two numbers"""
    return a + b

print(add(2, 3))
print(add.__name__)   # OOPS
print(add.__doc__)    # OOPS


Calling add with (2, 3)
5
wrapper
None


##### Example with @wraps

In [83]:
from functools import wraps

def debug(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print(f"Calling {func.__name__} with {args}")
        return func(*args, **kwargs)
    return wrapper

@debug
def add(a, b):
    """Add two numbers"""
    return a + b

print(add(2, 3))
print(add.__name__)   # ✅ "add"
print(add.__doc__)    # ✅ "Add two numbers"


Calling add with (2, 3)
5
add
Add two numbers


#### Example: Same Decorator on Two Functions

In [85]:
from functools import wraps

def debug(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print(f"Calling {func.__name__} with args={args}, kwargs={kwargs}")
        result = func(*args, **kwargs)
        print(f"{func.__name__} returned {result}")
        return result
    return wrapper

@debug
def add(a, b):
    return a + b

@debug
def multiply(a, b):
    return a * b

print(add(3, 4))
print(multiply(3, 4))


Calling add with args=(3, 4), kwargs={}
add returned 7
7
Calling multiply with args=(3, 4), kwargs={}
multiply returned 12
12


#### Another Example: Timing Any Function

In [87]:
import time
from functools import wraps

def timer(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"{func.__name__} took {end - start:.4f} seconds")
        return result
    return wrapper

@timer
def slow_square(n):
    time.sleep(1)
    return n * n

@timer
def slow_sum(n):
    time.sleep(2)
    return sum(range(n))

print(slow_square(5))
print(slow_sum(1000000))


slow_square took 1.0036 seconds
25
slow_sum took 2.0232 seconds
499999500000


### if elif else

In [89]:
x = 10

if x > 5:
    print("x is greater than 5")
print('_'*25)


x = 3
if x % 2 == 0:
    print("x is even")
else:
    print("x is odd")
print('_'*25)


score = 85

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
else:
    print("Grade: F")



x is greater than 5
_________________________
x is odd
_________________________
Grade: B


##### Nested if

In [91]:
x = 15

if x > 0:
    if x % 2 == 0:
        print("x is positive and even")
    else:
        print("x is positive and odd")
else:
    print("x is not positive")


x is positive and odd


#### Multiple Conditions (and, or, not)

In [93]:
age = 20
has_id = True

if age >= 18 and has_id:
    print("Access granted")
else:
    print("Access denied")


Access granted


#### Ternary Expression (one-line if/else)

In [95]:
x = 7
result = "Even" if x % 2 == 0 else "Odd"
print(result)


Odd


##### Real Example: Login System

In [97]:

username = "admin"
password = "1234"

if username == "admin" and password == "1234":
    print("Login successful ✅")
elif username == "admin":
    print("Wrong password ❌")
else:
    print("Unknown user 🚫")


Login successful ✅


##### Real Example: Traffic Light

In [99]:
light = "yellow"

if light == "green":
    print("Go 🚗")
elif light == "yellow":
    print("Slow down ⚠️")
elif light == "red":
    print("Stop 🛑")
else:
    print("Invalid signal ❓")


Slow down ⚠️


### Operators ==, !=, <=, >=, <, >

In [101]:
a, b = 5, 3

print(a == b)   # False
print(a != b)   # True



print(5 > 3)    # True
print(5 < 3)    # False
print(5 >= 5)   # True
print(3 <= 5)   # True



False
True
True
False
True
True


In [102]:
age = 20
has_id = True

if age >= 18 and has_id:
    print("Allowed ✅")
else:
    print("Denied ❌")


Allowed ✅


In [103]:
day = "Sunday"

if day == "Saturday" or day == "Sunday":
    print("Weekend 🎉")
else:
    print("Weekday 💼")


Weekend 🎉


In [104]:
logged_in = False

if not logged_in:
    print("Please log in 🔑")
else:
    print("Welcome back 👋")


Please log in 🔑


In [105]:
x = 15

if x > 10 and x < 20:
    print("x is between 10 and 20")

if x < 5 or x > 12:
    print("x is either less than 5 or greater than 12")

if not (x == 15):
    print("x is not 15")
else:
    print("x is 15 ✅")


x is between 10 and 20
x is either less than 5 or greater than 12
x is 15 ✅


### for loop

In [107]:
fruits = ["apple", "banana", "cherry"]

for fruit in fruits:
    print(fruit)


apple
banana
cherry


In [108]:
for letter in "hello":
    print(letter)


h
e
l
l
o


In [109]:
for i in range(5):   # 0 to 4
    print(i)

for i in range(2, 6):   # 2 to 5
    print(i)

for i in range(0, 10, 2):   # step of 2
    print(i)


0
1
2
3
4
2
3
4
5
0
2
4
6
8


In [110]:
# Looping with enumerate()
colors = ["red", "green", "blue"]

for index, color in enumerate(colors):
    print(index, color)


0 red
1 green
2 blue


In [111]:
# Looping over a dictionary

person = {"name": "Alice", "age": 25, "city": "NYC"}

for key, value in person.items():
    print(key, ":", value)


name : Alice
age : 25
city : NYC


In [112]:
# Nested loops

for i in range(1, 4):
    for j in range(1, 4):
        print(f"i={i}, j={j}")


i=1, j=1
i=1, j=2
i=1, j=3
i=2, j=1
i=2, j=2
i=2, j=3
i=3, j=1
i=3, j=2
i=3, j=3


In [113]:
# Using break and continue
nums = [1, 2, 3, 4, 5]

for n in nums:
    if n == 3:
        continue   # skip 3
    if n == 5:
        break      # stop at 5
    print(n)


1
2
4


In [114]:
# Loop with else
for n in range(5):
    print(n)
else:
    print("Loop finished without break")
# The else block runs only if the loop does not end with break

0
1
2
3
4
Loop finished without break


##### List Comprehension (short for loop)

In [116]:
squares = [x**2 for x in range(5)]
print(squares)
print('_'*25)

evens = [x for x in range(10) if x % 2 == 0]
print(evens)


[0, 1, 4, 9, 16]
_________________________
[0, 2, 4, 6, 8]


### while loop

In [118]:
# Infinite loop (⚠️ careful!)
# while True:
#     print("This runs forever!")


In [119]:
x = 1
while True:
    print(x)
    if x == 3:
        break   # exit loop
    x += 1


1
2
3


In [120]:
n = 0
while n < 5:
    n += 1
    if n == 3:
        continue   # skip printing 3
    print(n)


1
2
4
5


In [121]:
i = 1
while i <= 3:
    print("Loop", i)
    i += 1
else:
    print("Loop finished (no break)")


Loop 1
Loop 2
Loop 3
Loop finished (no break)


In [122]:
n = 1
while n <= 5:
    print(f"5 x {n} = {5*n}")
    n += 1


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25


### print with colors

##### Using ANSI Escape Codes (built-in)

In [125]:
# Format: \033[<style>;<text_color>;<background_color>m

print("\033[31mThis is Red Text\033[0m")
print("\033[32mThis is Green Text\033[0m")
print("\033[33mThis is Yellow Text\033[0m")
print("\033[34mThis is Blue Text\033[0m")
print("\033[35mThis is Magenta Text\033[0m")
print("\033[36mThis is Cyan Text\033[0m")
print("\033[37mThis is White Text\033[0m")


This is Red Text
This is Green Text
This is Yellow Text
This is Blue Text
This is Magenta Text
This is Cyan Text
This is White Text


##### Add Styles

In [127]:
print("\033[1;32mBold Green\033[0m")
print("\033[4;34mUnderlined Blue\033[0m")
print("\033[7;31mInverted Red\033[0m")


Bold Green
Underlined Blue
Inverted Red


##### With Background Colors

In [129]:
print("\033[30;47mBlack text on White background\033[0m")
print("\033[33;44mYellow text on Blue background\033[0m")


Black text on White background
Yellow text on Blue background


##### Using colorama (Windows friendly 🌐)-  (terminal only)

In [131]:
#pip install colorama)

from colorama import Fore, Back, Style, init
init(autoreset=True)  # auto reset after each print

print(Fore.RED + "Red text")
print(Fore.GREEN + "Green text")
print(Back.YELLOW + "With Yellow Background")
print(Style.BRIGHT + Fore.BLUE + "Bright Blue text")


Red text
Green text
With Yellow Background
Bright Blue text


##### Using termcolor - (terminal only)

In [133]:
# pip install termcolor

from termcolor import colored

print(colored("Hello in Red", "red"))
print(colored("Green on Yellow", "green", "on_yellow"))
print(colored("Bold Blue", "blue", attrs=["bold"]))


Hello in Red
Green on Yellow
Bold Blue


##### Use IPython display + HTML in Jupyter

In [135]:
from IPython.display import HTML, display

def cprint(text, color="red", bgcolor=None, bold=False):
    style = f"color:{color};"
    if bgcolor:
        style += f"background-color:{bgcolor};"
    if bold:
        style += "font-weight:bold;"
    display(HTML(f"<span style='{style}'>{text}</span>"))

cprint("Hello Red", color="red")
cprint("Green on Yellow", color="green", bgcolor="yellow")
cprint("Bold Blue", color="blue", bold=True)


### Use rich (best for modern notebooks & terminals) **************

In [137]:
# pip install rich

from rich import print as rprint

rprint('No color', end=" end ")
rprint("[red]Hello in Red[/red]", end=" ")
rprint("[green on yellow]Green on Yellow[/green on yellow]")
rprint("[bold blue]Bold Blue[/bold blue]")


No color end

Hello in Red

Green on Yellow

Bold Blue

# Dynamic Programming

## Fibonacci Numbers (Top-down with Memoization)
#### ✅ Uses recursion + memo dictionary to avoid recomputation.

In [140]:
def fib(n, memo={}):
    if n in memo:
        return memo[n]
    if n <= 1:
        return n
    memo[n] = fib(n-1, memo) + fib(n-2, memo)
    return memo[n]

print([fib(i) for i in range(10)])  # First 10 Fibonacci numbers


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


## Fibonacci (Bottom-up Tabulation)
#### Iterative and efficient.

In [142]:
def fib_tab(n):
    dp = [0, 1] + [0]*(n-1)
    for i in range(2, n+1):
        dp[i] = dp[i-1] + dp[i-2]
    return dp[n]

print(fib_tab(100))  # 55


354224848179261915075


## 🔹 Climbing Stairs (LeetCode Classic)
#### You can climb 1 or 2 steps at a time. How many ways to reach the top?

In [144]:
def climb_stairs(n):
    if n <= 2:
        return n
    dp = [0]*(n+1)
    dp[1], dp[2] = 1, 2
    for i in range(3, n+1):
        dp[i] = dp[i-1] + dp[i-2]
    return dp[n]

print(climb_stairs(5))  # 8


8


## 🔹 Coin Change (Minimum Coins)
#### Given coins [1, 2, 5] and amount 11, find min coins.

In [146]:
def coin_change(coins, amount):
    dp = [float("inf")] * (amount+1)
    dp[0] = 0
    for coin in coins:
        for x in range(coin, amount+1):
            dp[x] = min(dp[x], dp[x-coin] + 1)
    return dp[amount] if dp[amount] != float("inf") else -1

print(coin_change([1,2,5], 11))  # 3 (5+5+1)


3


## 🔹 Longest Common Subsequence (LCS)

In [148]:
def lcs(s1, s2):
    m, n = len(s1), len(s2)
    dp = [[0]*(n+1) for _ in range(m+1)]
    
    for i in range(m-1, -1, -1):
        for j in range(n-1, -1, -1):
            if s1[i] == s2[j]:
                dp[i][j] = 1 + dp[i+1][j+1]
            else:
                dp[i][j] = max(dp[i+1][j], dp[i][j+1])
    
    return dp[0][0]

print(lcs("abcde", "ace"))  # 3 ("ace")


3


In [149]:
# 🔹 0/1 Knapsack

In [150]:
def knapsack(weights, values, W):
    n = len(values)
    dp = [[0]*(W+1) for _ in range(n+1)]
    
    for i in range(1, n+1):
        for w in range(1, W+1):
            if weights[i-1] <= w:
                dp[i][w] = max(dp[i-1][w], values[i-1] + dp[i-1][w-weights[i-1]])
            else:
                dp[i][w] = dp[i-1][w]
    return dp[n][W]

print(knapsack([1,3,4], [15,20,30], 4))  # 35


35


# Algorithms

## 🔹 1. Bellman–Ford Algorithm

#### Works with negative weights.

#### Can detect negative weight cycles.

In [153]:
def bellman_ford(graph, V, src):
    # graph = [(u, v, w), ...]
    dist = [float("inf")] * V
    dist[src] = 0

    # Relax edges V-1 times
    for _ in range(V-1):
        for u, v, w in graph:
            if dist[u] != float("inf") and dist[u] + w < dist[v]:
                dist[v] = dist[u] + w

    # Detect negative cycles
    for u, v, w in graph:
        if dist[u] != float("inf") and dist[u] + w < dist[v]:
            print("Graph contains negative weight cycle!")
            return None

    return dist

# Example graph
edges = [
    (0, 1, -1), (0, 2, 4),
    (1, 2, 3), (1, 3, 2), (1, 4, 2),
    (3, 2, 5), (3, 1, 1), (4, 3, -3)
]
print(bellman_ford(edges, 5, 0))  # [0, -1, 2, -2, 1]


[0, -1, 2, -2, 1]


## 2. Dijkstra’s Algorithm

#### Works with non-negative weights.

#### Time complexity: O(E log V) with a priority queue (heap).

In [155]:
import heapq

def dijkstra(graph, src):
    # graph as adjacency list: {u: [(v, w), ...]}
    dist = {node: float("inf") for node in graph}
    dist[src] = 0
    pq = [(0, src)]  # (distance, node)

    while pq:
        d, u = heapq.heappop(pq)
        if d > dist[u]:
            continue
        for v, w in graph[u]:
            if dist[u] + w < dist[v]:
                dist[v] = dist[u] + w
                heapq.heappush(pq, (dist[v], v))
    return dist

graph = {
    0: [(1, 4), (2, 1)],
    1: [(3, 1)],
    2: [(1, 2), (3, 5)],
    3: []
}
print(dijkstra(graph, 0))  # {0: 0, 1: 3, 2: 1, 3: 4}


{0: 0, 1: 3, 2: 1, 3: 4}


## 3. Floyd–Warshall Algorithm

#### Finds all-pairs shortest paths.

#### Works with negative weights, but no negative cycles.

#### Time complexity: O(V³).

In [157]:
def floyd_warshall(matrix):
    V = len(matrix)
    dist = [row[:] for row in matrix]  # copy

    for k in range(V):
        for i in range(V):
            for j in range(V):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]
    return dist

INF = float("inf")
graph = [
    [0, 5, INF, 10],
    [INF, 0, 3, INF],
    [INF, INF, 0, 1],
    [INF, INF, INF, 0]
]

for row in floyd_warshall(graph):
    print(row)


[0, 5, 8, 9]
[inf, 0, 3, 4]
[inf, inf, 0, 1]
[inf, inf, inf, 0]
